export const sponsorsMetadata = {
    keywords: [
        "Red Logística",
        "Radio Red Logística",
        "logística argentina",
        "transporte argentina",
        "cadena de suministro argentina",
        "radio argentina",
        "programas de radio argentina",
        "podcast argentina",
        "comercio exterior argentina",
        "aduanas argentina",
        "puertos argentina",
        "aeropuertos argentina",
        "transporte terrestre argentina",
        "almacenamiento argentina",
        "distribución argentina",
        "tecnología logística argentina",
        "innovación logística argentina",
        "sostenibilidad logística argentina",
        "últimas noticias logística argentina",
        "tendencias logística argentina",
        "casos de éxito logística argentina",
        "entrevistas a expertos logística argentina",
        "análisis del mercado logístico argentino",
        "desafíos y oportunidades logística argentina",
        "logística Buenos Aires",
        "logística Córdoba",
        "logística Santa Fe",
        "logística Mendoza",
        "logística Rosario",
        "logística automotriz",
        "logística agropecuaria",
        "logística minera",
        "logística farmacéutica",
        "logística e-commerce",
    ],
    title: "Equipo de Radio Red Logística",
    description:
        "Conocé a nuestro equipo de Red Logística, tu pograma de Radio dónde encontrás entrevistas, noticias y más sobre logística.",
};